### ISSUE TITLE
Error : Cannot write to fd 

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdepends#149]
I understand this is still work in progress, but just thought I'd report that I can't get the example in the `README` to work:

``` r
library(pkgdepends)
pd <- new_pkg_deps("r-lib/cli")
pd$solve()
#> Warning: Unquoting language objects with `!!!` is deprecated as of rlang 0.4.0.
#> Please use `!!` instead.
#> 
#>   # Bad:
#>   dplyr::select(data, !!!enquo(x))
#> 
#>   # Good:
#>   dplyr::select(data, !!enquo(x))    # Unquote single quosure
#>   dplyr::select(data, !!!enquos(x))  # Splice list of quosures
#> 
#> This warning is displayed once per session.
#> Error : Cannot write to fd (system error 5, Access is denied.
#> ) @client.c:95
#> i Checking for package metadata updates
pd$draw()
#> Error in `$<-.data.frame`(`*tmp*`, "label", value = " ()"): replacement has 1 row, data has 0
```

<sup>Created on 2019-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2019-11-17                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                           
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                   
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                   
#>  callr         3.3.2      2019-09-22 [1] CRAN (R 3.6.1)                   
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                   
#>  cliapp        0.1.0      2018-12-16 [1] CRAN (R 3.5.2)                   
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                   
#>  curl          4.2        2019-09-24 [1] CRAN (R 3.6.1)                   
#>  debugme       1.1.0.9001 2019-01-19 [1] Github (r-lib/debugme@3c3c76d)   
#>  desc          1.2.0      2019-11-11 [1] Github (r-lib/desc@61205f6)      
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                   
#>  digest        0.6.22     2019-10-21 [1] CRAN (R 3.6.1)                   
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                   
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                   
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c)   
#>  filelock      1.0.2      2018-10-05 [1] CRAN (R 3.5.2)                   
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                   
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                   
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                   
#>  hms           0.5.2      2019-10-30 [1] CRAN (R 3.6.1)                   
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                   
#>  jsonlite      1.6        2018-12-07 [1] CRAN (R 3.6.0)                   
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.6.1)                   
#>  lpSolve       5.6.13.3   2019-08-19 [1] CRAN (R 3.6.1)                   
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                   
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                   
#>  pillar        1.4.2      2019-06-29 [1] CRAN (R 3.6.0)                   
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                   
#>  pkgcache      1.0.5      2019-05-31 [1] CRAN (R 3.6.0)                   
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                   
#>  pkgdepends  * 0.0.0.9006 2019-11-17 [1] Github (r-lib/pkgdepends@3f2ccd3)
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                   
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                   
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                   
#>  progress      1.2.2      2019-05-16 [1] CRAN (R 3.6.0)                   
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                   
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                   
#>  rappdirs      0.3.1      2016-03-28 [1] CRAN (R 3.5.1)                   
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                   
#>  rematch2      2.1.0      2019-07-11 [1] CRAN (R 3.6.1)                   
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                   
#>  rlang         0.4.1      2019-10-24 [1] Github (r-lib/rlang@30feeac)     
#>  rmarkdown     1.17       2019-11-13 [1] CRAN (R 3.6.1)                   
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                   
#>  selectr       0.4-1      2018-04-06 [1] CRAN (R 3.5.1)                   
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                   
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                   
#>  testthat      2.3.0      2019-11-05 [1] CRAN (R 3.6.1)                   
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                   
#>  usethis       1.5.1.9000 2019-11-13 [1] Github (r-lib/usethis@c5f1e7f)   
#>  uuid          0.1-2      2015-07-28 [1] CRAN (R 3.5.0)                   
#>  vctrs         0.2.0      2019-07-05 [1] CRAN (R 3.6.1)                   
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                   
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.6.1)                   
#>  xml2          1.2.2      2019-08-09 [1] CRAN (R 3.6.1)                   
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                   
#>  zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.5.1)                   
#>  zip           2.0.4      2019-09-01 [1] CRAN (R 3.6.1)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

**Comment by gaborcsardi** [comment]
Fixed in callr: https://github.com/r-lib/callr/issues/132

**Comment by IndrajeetPatil** [comment]
Thanks, but I still can't get this to work (devel versions of both `cli` and `pkgdepends`):

``` r

library(pkgdepends)
pd <- new_pkg_deps("r-lib/cli")
pd$solve()

#> Warning: Unquoting language objects with `!!!` is deprecated as of rlang 0.4.0.
#> Please use `!!` instead.
#> 
#>   # Bad:
#>   dplyr::select(data, !!!enquo(x))
#> 
#>   # Good:
#>   dplyr::select(data, !!enquo(x))    # Unquote single quosure
#>   dplyr::select(data, !!!enquos(x))  # Splice list of quosures
#> 
#> This warning is displayed once per session.
#> i Checking for package metadata updates

pd$draw()
#> Error: Cannot install packages:
#>   x Cannot install `r-lib/cli`.
#>     - attempt to apply non-function
```

<sup>Created on 2019-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2019-12-23                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                           
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                   
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                   
#>  callr         3.4.0      2019-12-09 [1] CRAN (R 3.6.1)                   
#>  cli         * 2.0.0.9000 2019-12-23 [1] Github (r-lib/cli@0293ae7)      
#>  cliapp        0.1.0      2018-12-16 [1] CRAN (R 3.5.2)                   
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                   
#>  curl          4.3        2019-12-02 [1] CRAN (R 3.6.1)                   
#>  debugme       1.1.0.9001 2019-01-19 [1] Github (r-lib/debugme@3c3c76d)   
#>  desc          1.2.0      2019-11-11 [1] Github (r-lib/desc@61205f6)      
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                   
#>  digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                   
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                   
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                   
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c)   
#>  filelock      1.0.2      2018-10-05 [1] CRAN (R 3.5.2)                   
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                   
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                   
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                   
#>  hms           0.5.2      2019-10-30 [1] CRAN (R 3.6.1)                   
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                   
#>  jsonlite      1.6        2018-12-07 [1] CRAN (R 3.6.0)                   
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.6.1)                   
#>  lpSolve       5.6.13.3   2019-08-19 [1] CRAN (R 3.6.1)                   
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                   
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                   
#>  pillar        1.4.3      2019-12-20 [1] CRAN (R 3.6.1)                   
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                   
#>  pkgcache      1.0.5      2019-05-31 [1] CRAN (R 3.6.0)                   
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                   
#>  pkgdepends  * 0.0.0.9006 2019-12-23 [1] Github (r-lib/pkgdepends@1c6869c)
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                   
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                   
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                   
#>  progress      1.2.2      2019-05-16 [1] CRAN (R 3.6.0)                   
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                   
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                   
#>  rappdirs      0.3.1      2016-03-28 [1] CRAN (R 3.5.1)                   
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                   
#>  rematch2      2.1.0      2019-07-11 [1] CRAN (R 3.6.1)                   
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                   
#>  rlang         0.4.2      2019-11-23 [1] CRAN (R 3.6.1)                   
#>  rmarkdown     2.0        2019-12-12 [1] CRAN (R 3.6.1)                   
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                   
#>  selectr       0.4-2      2019-11-20 [1] CRAN (R 3.6.1)                   
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                   
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                   
#>  testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.1)                   
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.1)                   
#>  usethis       1.5.1.9000 2019-12-12 [1] Github (r-lib/usethis@23dd62c)   
#>  uuid          0.1-2      2015-07-28 [1] CRAN (R 3.5.0)                   
#>  vctrs         0.2.1      2019-12-17 [1] CRAN (R 3.6.1)                   
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                   
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.6.1)                   
#>  xml2          1.2.2      2019-08-09 [1] CRAN (R 3.6.1)                   
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                   
#>  zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.5.1)                   
#>  zip           2.0.4      2019-09-01 [1] CRAN (R 3.6.1)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

Traceback:
```r
> traceback()
6: stop("Cannot install packages:\n", msg, call. = FALSE)
5: pkgplan_stop_for_solve_error(self, private)
4: self$stop_for_solve_error()
3: pkgplan_draw_solution_tree(self, private, pkgs, types, annotate)
2: private$plan$draw_solution_tree()
1: pd$draw()
```
